# Generated by Django 2.2 on 2019-04-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20190409_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('post_detail', models.TextField()),
                ('request_num', models.IntegerField()),
                ('accept_num', models.IntegerField(default=0)),
                ('deadline', models.DateField()),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('if_end', models.BooleanField(default=False)),
                ('poster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
            options={
                'ordering': ['post_time'],
            },
        ),
    ]
