# Generated by Django 2.2 on 2019-05-03 16:42

import demand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(max_length=256, null=True, upload_to=demand.models.post_image_path),
        ),
    ]
