# Generated by Django 2.2 on 2019-04-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_auto_20190411_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.DateField(auto_now_add=True),
        ),
    ]
