# Generated by Django 2.2 on 2019-05-04 18:02

import demand.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demand.Post'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='resume',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Resume'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='D:\\Projects\\Pycharm\\GroupWork\\backend\\media\\img/post/example/1.jpg', max_length=256, upload_to=demand.models.post_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
    ]
