# Generated by Django 2.2 on 2019-04-11 09:46

import demand.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190409_1518'),
        ('demand', '0003_auto_20190411_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(max_length=256, upload_to=demand.models.resume_file_path)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demand.Post')),
            ],
        ),
    ]
