# Generated by Django 2.2 on 2019-04-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0004_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='resume',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_detail',
            field=models.TextField(default=''),
        ),
    ]
