# Generated by Django 2.2 on 2019-04-12 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0005_auto_20190412_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'ordering': ['c_time']},
        ),
        migrations.AddField(
            model_name='apply',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
