# Generated by Django 2.2 on 2019-04-21 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('degree', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('awards', models.TextField(blank=True)),
                ('english_skill', models.TextField(blank=True)),
                ('edu_exp', models.TextField(blank=True)),
                ('project_exp', models.TextField(blank=True)),
                ('self_review', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=0)),
                ('student_id', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=32)),
                ('major', models.CharField(max_length=64)),
                ('grade', models.CharField(max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Resume')),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
    ]
