# Generated by Django 2.2 on 2019-04-09 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(default=datetime.datetime(2019, 4, 9, 7, 18, 0, 775706, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default=datetime.datetime(2019, 4, 9, 7, 18, 17, 590052, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=datetime.datetime(2019, 4, 9, 7, 18, 20, 399439, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default=datetime.datetime(2019, 4, 9, 7, 18, 22, 808057, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default=datetime.datetime(2019, 4, 9, 7, 18, 25, 273639, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
    ]
