# Generated by Django 2.2 on 2019-05-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='open_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
