# Generated by Django 2.2 on 2019-04-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190409_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('education', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('awards', models.TextField(blank=True)),
                ('english_skill', models.TextField(blank=True)),
                ('edu_exp', models.TextField(blank=True)),
                ('project_exp', models.TextField(blank=True)),
                ('self_review', models.TextField(blank=True)),
            ],
        ),
    ]
