# Generated by Django 2.2 on 2019-04-13 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Resume'),
        ),
    ]
