# Generated by Django 2.2 on 2019-04-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='education',
            new_name='degree',
        ),
        migrations.AlterField(
            model_name='resume',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
